language: r

sudo: false

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - valgrind
      - libapparmor-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra
      - libmagick++-dev
      

r_github_packages:
  - jimhester/covr
  - ropensci/pdftools
  - trinker/textshape

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

