language: r

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      sudo: required
    - os: osx
      osx_image: xcode8.1
      brew_packages: poppler
      latex: false
    - os: osx
      osx_image: xcode8.1
      disable_homebrew: true
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - valgrind

before_install:
  - sh -e /etc/init.d/xvfb start

r_github_packages:
  - jimhester/covr
  - ropensci/pdftools
  - trinker/textshape

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

